### ISSUE TITLE
Effection Logo Proposal

### ISSUE THREAD

**Issue by minkimcello** [thefrontside/effection#111]
## Context
Effection could use a logo and Effection's [Discord channel](https://discord.gg/Ug5nWH8) gets buried very quickly with other discussion so I've decided to post a Github issue for it instead.

## Approach
*Disclaimer: Not a design person but we must do what we must do in these trying times... and also it's sort of fun.*
### Fundamentals
- Use Frontside brand colors.
- Incorporate six edges like the `Frontside`, `BigTest`, and `Microstates`.
- Keep it abstract, compact, and cute; should be simple enough doodle easily.
- Effection is "affection" ❤️. End of story. Non-negotiable.

### Explored Options
1. Nodes with arrows
![nodes-arrow](https://user-images.githubusercontent.com/29791650/80426527-e32b2300-88b3-11ea-83d6-f6c219256f5f.png)
- Not compact enough without making it look like bowling ball finger holes.
- There are a LOT of these node-type logos out there and so is not unique.

2. Stacked with arrows
![stacks-arrows](https://user-images.githubusercontent.com/29791650/80426612-11106780-88b4-11ea-8fab-f33838130b0f.png)
- Just like the node-type logos, the 3-stack logos are very common too and is often used for data-related companies.
- Changing the stacks to hearts and adding arrows on top of that will result in something too complex for a logo.

## Proposal
Follows all the fundamentals listed above: easy to doodle, six edges, heart-shape:
![proposed](https://user-images.githubusercontent.com/29791650/80426936-c511f280-88b4-11ea-961a-f4b3cc2525bc.png)

I've tried adding different borders and shadows but given the navy outline the shadows didn't have the ~~effection~~ effect we wanted and the borders just took away from the simplicity of the design without adding value (in my opinion):
![borders](https://user-images.githubusercontent.com/29791650/80427221-3fdb0d80-88b5-11ea-9af0-afb75c1b4459.png)

I've also tried different size variations. I find the 120 to be the right amount of bubbly:
![size var](https://user-images.githubusercontent.com/29791650/80427276-639e5380-88b5-11ea-8899-5e077f475f9c.png)

And variation of different edges:
![edges](https://user-images.githubusercontent.com/29791650/80500980-e1f20880-893c-11ea-84ee-65b92919f176.png)

And here's what the logo would look like with the rest of the Frontside brands:
![altogether](https://user-images.githubusercontent.com/29791650/80427322-7d3f9b00-88b5-11ea-9c61-256c901805c6.png)

**Comment by jorgelainfiesta** [comment]
Looks great! My only observation would be that Affection's logo has rounded borders on the outline while none of the other logos do. Actually, none of the logos have any rounded corners but I'm not sure how the heart could be constructed with those constrains.

**Comment by minkimcello** [comment]
@jorgelainfiesta Here's what sharp edges would look like (added up top too). And I made one with even rounder edges.

![edges](https://user-images.githubusercontent.com/29791650/80501077-00f09a80-893d-11ea-81fc-cc58dd52475b.png)

**Comment by jorgelainfiesta** [comment]
The sharp edges look pretty weird. I like the rounder edges the best.

What if we did sharp edges only (even the internal ones)? might require adjusting a bit the shape of things.

**Comment by minkimcello** [comment]
![edges v2](https://user-images.githubusercontent.com/29791650/80807341-f1ff2780-8b8a-11ea-9f8c-33fbb7e6a321.png)

**Comment by minkimcello** [comment]
I've been going back and forth with a designer regarding this logo. She created some rough drafts (there were a few others but I just picked the ones that were appropriate because not all of them fit the criteria):

<img width="673" alt="Screen Shot 2020-06-03 at 4 23 20 PM" src="https://user-images.githubusercontent.com/29791650/83685371-8f98ad00-a5b6-11ea-949f-e2d30e54f5cd.png">

Her feedback was as follows:
1. Round edges = softer and cuter.
2. Border size = 120 is well balanced.
3. She also suggested possibly using symmetrical boxes as opposed to overlapping boxes (you can see an example on the bottom left of the four logos).

My two cents: I think if we want the matching sharp edges we go with the `sharp sharp` or if we don't mind this logo having round edges unlike the other logos we can go with `round edges` (from the comment above this one). At least as a placeholder.

**Comment by cowboyd** [comment]
What if she were to experiment with an isometric view instead of top-down?

**Comment by minkimcello** [comment]
@cowboyd I asked the designer to sketch some isometric logos and she came back with these. Were these what you had in mind?

![IMG_8659](https://user-images.githubusercontent.com/29791650/84789794-a085ed00-afbe-11ea-89e2-9d2d483c8dfe.jpeg)

**Comment by cowboyd** [comment]
They were indeed. Very cool indeed. I'd also love to see what they come up with completely free of any context from us other than our current set of logos. As in, are there any completely novel approaches to depicting the "emotive force of causation" coupled with love.

P.S.I wouldn't expect that they should work for free.

**Comment by minkimcello** [comment]
Here are some of the other ones that she previously showed me. There was a bit of a miscommunication in the beginning by what we meant by "unifying" the logos so that's why she thought the Effection logo needed to be similar to the Frontside logo:
![IMG_8167](https://user-images.githubusercontent.com/29791650/84791971-57836800-afc1-11ea-9b20-88712497ec17.jpeg)

And some other ones that didn't follow the six-edges rule or overlapping "nodes" concept:
![IMG_8472](https://user-images.githubusercontent.com/29791650/84791972-57836800-afc1-11ea-80e6-18c3cc1c3fc2.jpeg)

> P.S.I wouldn't expect that they should work for free.

I had her invoice my corporation because she's based in Canada and also because I wanted to front the risk just in case. If and once we decide on a logo I'll just add it as an expense on my invoice to Frontside. Her hourly rate is very modest. 👌

**Comment by jnicklas** [comment]
Since we're now working on the website and stuff, it feels like we should come to a conclusion here? Personally I like the original proposal. This one:

![80426936-c511f280-88b4-11ea-961a-f4b3cc2525bc](https://user-images.githubusercontent.com/134/122924369-f9bcf500-d365-11eb-8a20-eb9bc5882048.png)

It feels balanced, clean, well designed, and in line with the branding of other frontside projects.

**Comment by jorgelainfiesta** [comment]
My illustration sucks, but perhaps we can experiment with the composability concept as part of the isometric line? Like we can have the heart on plane 0, pink large piece and sky blue on plane 1, and white piece on plane 2. Or we can flatten it to two planes. 

![Screenshot 2021-07-08 at 11 24 29](https://user-images.githubusercontent.com/4451393/124898005-1b151680-dfdf-11eb-8061-aca465839344.png)

**Comment by minkimcello** [comment]
> My illustration sucks, but perhaps we can experiment with the composability concept as part of the isometric line? Like we can have the heart on plane 0, pink large piece and sky blue on plane 1, and white piece on plane 2. Or we can flatten it to two planes.

Yeah I see what you're saying. That's why the original logo I proposed has rounded edges. You can tell the white and blue boxes are larger than what you can see.

![Screen Shot 2021-07-08 at 6 50 42 AM](https://user-images.githubusercontent.com/29791650/124909802-e1c9b000-dfb8-11eb-8bfb-96283b01a196.png)

I don't know too much about design but I think 3d logos are hard to pull off. It should be easy to sketch on a notepad while you're talking on the phone. 🤷‍♂️

**Comment by jorgelainfiesta** [comment]
Ah gotcha! then I'd go with either of these. Should we make like a poll on discord to decide? not sure how to short list the options tho. Maybe just vote among the 4 that you posted on Jun 3rd?
![Screenshot 2021-07-08 at 17 52 59](https://user-images.githubusercontent.com/4451393/124953365-60543b00-e015-11eb-9ffb-d332e943e945.png)

**Comment by minkimcello** [comment]
@jorgelainfiesta I personally like the one Jonas picked. It's the most well balanced. But we should probably hear from Charles too before we post it on Discord. I think he might have an opinion on what the logo should be.

**Comment by cowboyd** [comment]
I'm ok with that! I also like the one that you did for the docs website

<img width="152" alt="blurred effection logo" src="https://user-images.githubusercontent.com/4205/125128463-aec01300-e0c3-11eb-81e6-d5eb518d6474.png">


I know that was just a placeholder, but it's kind of awesome.

**Comment by jnicklas** [comment]
Another week with no decision on this. I have no idea if I have the authority to do this, but I'm tired of waiting for this, so I'm just deciding that this is the logo for Effection:

![122924369-f9bcf500-d365-11eb-8a20-eb9bc5882048-2](https://user-images.githubusercontent.com/134/136526084-7a017797-299d-4b8e-af0a-93c4165d81b0.png)
