### ISSUE TITLE
Should implicit wait for concurrent tasks be made explicit? i.e. should `fork` go away?

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/effection#118]
The difference between `spawn` and `fork` is a subtle one, and I'm dreading having to write the tutorials that explains the _why_ of `spawn` vs `fork`. It's difficult to explain because `fork` does a lot of implicit magic.

The only difference between

```ts
function * withFork() {
  let child = fork(function*() {
    yield doStuff();
  });
  return 'done'
}
```

and 

```ts
function * withSpawn() {
  let child = spawn(function*() {
    yield doStuff();
  });
  return 'done';
}
```

Is that `withSpawn` will return `'done'` to its parent immediately, where as `withFork` will return `'done'` to its parent only after `doStuff()` has finished. Unless you're familiar with the ins and outs of effection, this is a very surprising result. I have to imagine that this would be a major sticking point to adoption.

It's interesting to me that `withFork` could be re-written using `spawn()` plus an explicit wait, and it's a lot clearer what's going on just by looking at the code.

```ts
function * withSpawnAndWait() {
  let child = spawn(function*() {
    yield doStuff();
  });
  yield child;
  return 'done';
}
```

Which makes me think: "man, fork() has some seriously non-local effects, so what kind of weight is that abstraction carrying exactly?"

Given our experience with BigTest has shown that 90% of the time what we want is actually the non-blocking `spawn()` perhaps we should consider deprecating `fork` entirely and migrate existing code to using explicit, rather than implicit wait.

**Comment by jnicklas** [comment]
Maybe this is mostly a question of naming? `fork` does not give any indication about the fact that it would block until completion (in fact kind of the opposite imo), maybe something like `spawnBlocking` or `spawn(..., { blocking: true })` would be clearer?

I just did a quick check how often we use `fork` in BigTest, and IMO, the most interesting usage of `fork` is in the command processor. Granted, this is something which is on the kill list anway, but I think the pattern is interesting!

``` typescript
export function* createCommandProcessor(options: CommandProcessorOptions): Operation {
  while(true) {
    let message = yield options.commands.receive({ type: 'run' });
    yield fork(run(message, options));
  }
}
```

Let's expand on this a bit to show why `fork` is useful in this case:

``` typescript
export function* createCommandProcessor(options: CommandProcessorOptions): Operation {
  while(true) {
    let message = yield options.commands.receive({ type: 'run' });
    if(message.type === 'close') {
      break;
    } else {
      yield fork(run(message, options));
    }
  }
}
```

In this case, the behaviour that we probably want is for the command processor to finish processing any messages which are still in flight, when it receives a close message. This pattern is easy to implement with `fork`, but gets pretty messy and strange when implemented with `spawn`.

Also, once we have async teardown, `fork` or `spawnBlocking` can be implemented as a library:

``` typescript
function spawnBlocking<T>(parent: Task<T>, operation: Operation<T>): Task<T> {
  let child = parent.spawn(operation);
  parent.spawn(function*() {
    try {
      yield;
    } finally {
      yield child;
    }
  });
  return child;
}
```

**Comment by jnicklas** [comment]
Actually never mind that, the above idea of implementing `fork` as a library is not equivalent in functionality. The difference is whether or not we `halt` the child. The spawned child will always be halted when the parent is complete. Awaiting blocking children is different because we do not halt them, but rather wait for them to complete "naturally".

I think the above comment makes a good case for some kind of blocking spawn being useful, and actually pretty tricky to implement correctly, so it probably *is* something we should preserve?

**Comment by jnicklas** [comment]
So I spent some more time thinking about this, and I've come to the conclusion that `fork` is indeed sometimes useful and that implementing this *correctly* in user land is very, very difficult. There are edge cases around halting which are simply not easily handled. So I believe that `fork` should stay, but that the emphasis should be on `spawn` which should be the *normal* method to call, with `fork` being reserved for edge cases.

I've added support for `fork` in mini-effection here: https://github.com/jnicklas/mini-effection/pull/10

**Comment by cowboyd** [comment]
I wonder if we could clear up some of the confusion by not using `fork` which is an overloaded term and is pretty much synonymous with `spawn` and our assignment of what they mean in the library is arbitrary.

what if we called it something like `append()`, `include()`, or `extend()` meaning that this operation is actually part of the workload of the current operation. `spawn()` and `fork()` both have the connotation of "creating a child", and while the underlying mechanics of Effection may use our internal child/link mechanism, the semantics are more akin to expanding the scope of the _current task_ at runtime.

In fact, we may even find that as a matter of implementation that it is simpler to consider a task to be 1 or more concurrently running operations and that the task is finished once all of its operations are complete. `fork()`, `include()`, or  would then just append an operation to the current task.

**Comment by jnicklas** [comment]
`v2` does include a `fork` like mechanism, but it is not called `fork`. Instead it is the `blockParent` option on a task.
