### ISSUE TITLE
Rename `main` method to `run` or `enter` (or something else)

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/effection#130]
Right now, there are two `main`s. One from `@effection/node` and another from `effection`, which is confusing. I think that `main` is the understood term as an entry point to an entire process, so `@effection/node` `main` should stay the same since that really is its purpose.

That means we really ought to come up with a better name for it in `effection` proper. I'm thinking that we should call it `run` or `enter`. It should convey that you are entering _an_ effection entry point, but not necessarily for the entire process.

**Comment by jnicklas** [comment]
I like `run`, it feels very short and concise.

**Comment by cowboyd** [comment]
@jnicklas I agree. Short, concise, and intuitive👍 

@taras while technically you _can_, have several `run`s in a process tree since `run` would convert an operation into what amounts to a promise, you would never do it, since if you're already in an effection context, running a subtask is as simple as `yield`ing to an operation, and you get all the benefits of scoping and cancellation.

Where it could happen is if you have two completely separate libraries, that are not connected using effection, they could each use `run` internally.

What's not allowed, is using more than one `main` from `@effection/node` per node-process since it installs global signal handlers and has hard hooks to `process.exit()`

**Comment by cowboyd** [comment]
I'm going to update this with the [good first issue](https://github.com/thefrontside/effection/labels/good%20first%20issue) label if anybody wants to tackle it.
