### ISSUE TITLE
Fluid interface for subscribable types?

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/effection#143]
The `Subscribable` interface defines a minimal interface which a type must conform to in order to be subscribable. This means you can always use `Subscribable.from(...)` to get the nice chainable interface. However, while it shouldn't be mandatory, sometimes it would be nice to actually implement the full set of chainable operations on a type directly. As I'm porting channels to the new subscriptions, I found this to be the case. Instead of having to write:

``` typescript
let myChannel = new Channel();
yield Subscribable.from(myChannel).map((value) => value * 2).first();
```

It would be much nicer to be able to call `map` directly on the channel:

``` typescript
let myChannel = new Channel();
yield myChannel.map((value) => value * 2).first();
```

But this requires actually adding `map` to the Channel type. In the interest of not having there be any compability problems, and uniformity across types in the ecosystem, maybe we should provide an additional interface which extends `Subscribable` that types can implement, which also defines the `map` and `filter` methods and so on.

All of the actual implementations would of course simply delegate to `Subscribable.from(this).map(fn)` and so on.

**Comment by jnicklas** [comment]
@cowboyd what do you think? I'm a bit torn on whether I feel that this is a good idea. It does make actually using subscribable types much more pleasant, but it also adds some overhead.

**Comment by jnicklas** [comment]
An alternative is to provide `map` and `filter` and such as free functions as well:

``` typescript
let myChannel = new Channel();
yield map(myChannel, (value) => value * 2).first();
// or maybe more functional like this?
yield map((value) => value * 2, myChannel).first();
```

**Comment by jnicklas** [comment]
> Ideally what you would get back from Channel#map would also be a channel. In fact, if we're talking hardcore FP, the Functor laws would require it.

Wouldn't this be a bit odd? What does this do:

``` typescript
let channel = new Channel<number>();
let mapped = channel.map((num) => num * 2)

mapped.send(4); // ????
```

**Comment by cowboyd** [comment]
I see. Yeah that would be weird. It only really makes sense in the case with separate types for send and receive.
