### ISSUE TITLE
Wrapping with `ChainableResource` strips resources

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/effection#167]
There is a subtle bug in how #155 is implemented.

It is quite common to return a resource as a subscription, like this:

``` typescript
class Something {
  *[SymbolSubscribable]() {
    return yield resource(...);
  }
}
```

The problem comes in the way that the `subscribe` function is implemented in `@effection/subscription`. Somewhat simplified it boils down to:

``` typescript
function* subscribe(source) {
  let inner = yield source[SymbolSubscribable]();
  return new ChainableSubscription(inner);
}
```

The problem here is that the resource is bound to the context inside the subscribe function, and it is *not* returned from this context, meaning it will expire when subscribe exits. This is of course wrong.

**Comment by jnicklas** [comment]
Having `ChainableSubscription` is *sooo* convenient, but I'm not sure what to do about this issue. Possible workarounds are a bit ugly.

**Comment by cowboyd** [comment]
> The problem here is that the resource is bound to the context inside the subscribe function, and it is _not_ returned from this context, meaning it will expire when subscribe exits. This is of course wrong.

This is actually a problem we're going to have to solve long term in effection since a [similar dynamic is at play here](https://github.com/thefrontside/effection/pull/156#issuecomment-648283944). We need to have a wait to maintain resource chains, or "hand off" resource batons from user-space.
