### ISSUE TITLE
make default `TReturn` of subscription `undefined`

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/effection#176]
It's very common to use "infinite" streams that have the same lifetime as the operation that consumes them. In fact, in the wild thus far, this is more common than actually having a meaningful return value. It's a pain then to have the `Subscription` interface always need to specify two generic parameters, `T` and `TReturn` every time. If most of the time a subscription is infinite, then it probably makes sense to default it to `undefined`

**Comment by jnicklas** [comment]
Yes, please!

**Comment by dagda1** [comment]
should `TReturn` not default to `void` instead of `undefined`?

I also have a pedantic request :).

I think the prefixing of types with `T` as in `TReturn` does not help readability IMHO.

Where possible we should an uppercase single letter so `R` is a better candidate than `TReturn`.

**Comment by cowboyd** [comment]
> Where possible we should an uppercase single letter so R is a better candidate than TReturn.

This is how MS does the typing of its `Iterator` and `Iterable` class, so that's the convention that we followed. It seems to be that when you have a channel whose `R` is `void`, you can't just say `close()`, instead you have to say `close(null)` or `close(undefined)` which kinda stinks.

**Comment by dagda1** [comment]
@cowboyd I think you make a valid point that this is what is used in the `IteratorResult`. 

I still prefer `R` but what you say makes sense.

> instead you have to say close(null) or close(undefined) which kinda stinks.

You could have 

```ts
type Nothing = undefined | null;`

Subscription<T, TReturn = Nothing>
```

But I totally understand the case now, so thanks for clearing that up.

**Comment by cowboyd** [comment]
That could also work. I actually much prefer `Nothing` to `undefined`. Kinda wish `void` was an alias for that since that's what I thought it was for the longest time.
