### ISSUE TITLE
Make tests run on windows

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/effection#181]
For good cross platform support, we should make sure our tests run on windows

**Comment by jbolda** [comment]
Is the expectation to run it in CircleCI?

**Comment by cowboyd** [comment]
We run our tests on github actions, so expectation would be for them to run there. I believe @taras made a little headway getting the windows VM setup ther.

**Comment by taras** [comment]
Not much headway, I thought GitHub Supports Windows server. Can we use that? Otherwise we can use CircleCI

**Comment by jbolda** [comment]
Aye, it does @taras. I am way more familiar with Github Actions so I can open a PR to switch it over.

**Comment by cowboyd** [comment]
closed by #202
