### ISSUE TITLE
Problems spawning processes in Windows

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/effection#182]
When you spawn a child process in windows,

1. it does not die when you call process.kill
2. causes a separate window to open up every time

Potentially related https://stackoverflow.com/questions/32705857/cant-kill-child-process-on-windows ?

Consider using [execa] ? 

[1]: https://github.com/sindresorhus/execa

**Comment by taras** [comment]
execa looks like a good way to go. I tried cross-spawn and it doesn't support SIGTERM, hopefully execa does.

**Comment by taras** [comment]
For reference https://github.com/nodejs/node/issues/12378

**Comment by jbolda** [comment]
In execa, it tries SIGTERM and if no response then falls back to SIGKILL.
https://github.com/sindresorhus/execa#killsignal-options

Seems to be the quickest win here. Drop in execa and if in the future more control is required, back it out with good test coverage.

<blockquote><img src="https://repository-images.githubusercontent.com/47475908/a11f9000-b3ba-11e9-97db-972f10afb149" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/sindresorhus/execa">sindresorhus/execa</a></strong></div><div>Process execution for humans. Contribute to sindresorhus/execa development by creating an account on GitHub.</div></blockquote>

**Comment by cowboyd** [comment]
@jbolda agree, let's see if we can just use execa.
