### ISSUE TITLE
Improve Subscription developer experience

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/effection#183]
Over the last 6 weeks, we've had the opportunity to work with Subscriptions a lot and while it has on the whole been positive, it has also made clear that there are still a bunch of rough edges.

I've observed the following:

1. Transforming subscriptions on both sides of the `yield` is desirable. There are cases where it just makes sense to have both:

```ts
let subscription: Subcription = yield Subscribable.from(source).map(x).filter(y)
let next = yield subscription.next();
```

```ts
let subscription: ChainableSubscription = yield subscribe(source);
let next = yield subscription.map(x).filter(y).next();
```

2. There are too many damn interfaces, classes and functions in the API, and it's confusing to explain which is which. `Subscribable`, `Subscription`, `subscribe()`, `ChainableSubscription`, `Chain`. If you want to move seemlessly from left-side chaining,  to right-side chaining, you have to completely change all the names and imports that you're using.

What would be really awesome is to just have just two interfaces `SubscriptionTransformer` and `Subscription` (which extends `SubscriptionTransformer`), and a single function `subscribe` which can be used on both the left and right sides of the `yield`.

Thus, you could say:

```ts
let subscription: Subscription = yield subscribe(source).map(X);
yield subscription.filter(Y).next();
```

In practice, folks would really only need to know about the `Subcription` interface and the `subscribe` function, which would grossly simplify trying to explain how to work with them.

The type declarations could look like:

```ts
export interface SubscriptionTransformer<T,TReturn> {
  filter(predicate: (value: T) => boolean): SubscriptionTransformer<T, TReturn>;

  match(reference: DeepPartial<T>): SubscriptionTransformer<T,TReturn>;

  map<R>(mapper: (value: T) => R): SubscriptionTransformer<R, TReturn>;

  first(): Operation<T | undefined>;

  expect(): Operation<T>;

  forEach(visit: (value: T) => Operation<void>): Operation<TReturn>;
}

export interface SubscriptionIterator<T, TReturn> {
  next(): IteratorResult<T,TReturn>;
}

export type Subscription<T,TReturn> = SubscriptionTransformer<T,TReturn> & SubscriptionIterator<T,TReturn>;
```

On the right side, the object returned by `subscribe` would be a `SubscriptionTransformer`, and on the left, it would be a `Subscription`

There is one catch however, we need to be able to treat this `SubscriptionTransformer` on the right side of the yield as an operation which is currently not possible in effection.  As it stands, `subscribe()` can't return anything smart. However, if we supported a `ToOperation` symbol to allow any object to be treated as an operation, then we could achieve it by making the `subscribe` function return a `SubscriptionTransformer` that was also an operation:

```ts
export declare function subscribe(source: SubscriptionSource): SubscriptionTransformer & Operation<Subscription>
```

**Comment by jnicklas** [comment]
Isn't this precisely what we've done with #178, or am I misunderstanding what you want to achieve?

**Comment by jnicklas** [comment]
Ahh okay, I read this again, and I think I see what you're seeing. I don't think what you want is currently possible with TypeScript, since it would require higher kinded types, which TypeScript currently doesn't support.

This is a very stripped down version of the types currently in use, with the addition of `ChainableSubscriptionMethods` which is just there to simplify thinking about this:

``` typescript
import { Operation } from 'effection';

export interface ChainableSubscriptionMethods<T,TReturn> {
  filter(): ChainableSubscription<T, TReturn>;
}

export class ChainableSubscription<T,TReturn> implements ChainableSubscriptionMethods<T, TReturn> {
  filter(): ChainableSubscription<T, TReturn> {
    throw new Error("not implemented");
  }
}

export interface ChainableSubscribableMethods<T,TReturn> {
  filter(): ChainableSubscribable<T, TReturn>;
}

export type ChainableSubscribable<T, TReturn> = Operation<ChainableSubscription<T, TReturn>> & ChainableSubscribableMethods<T, TReturn>;
```

If I'm understanding you right, what you want is an interface which is implemented by both `ChainableSubscriptionMethods` and `ChainableSubscribableMethods` so that we don't have to know the concrete type but can still use either method to transform them. In the first place, this is tricky, since erasing the concrete type means that we lose the property of a chainable subscribable being an operation, but like you said this might be solvable with some kind of `toOperation` thing (and having that be part of the common interface).

But here is the even more challenging part: how would we write such an interface? As far as I can tell, there is no way of doing this in current TypeScript. Here it is written with `*<...>` as pseudo syntax for a higher kinded type constraint:

``` typescript
interface ChainableMethods<RETURN extends *<T, TReturn>> {
  filter(predicate: (value: T) => boolean): RETURN
}

interface ChainableSubscribableMethods<T,TReturn> implements ChainableMethods<ChainableSubscribable<T, TReturn>>  {
  filter(predicate: (value: T) => boolean): ChainableSubscribable<T, TReturn>;
}

interface ChainableSubscriptionMethods<T,TReturn> implements ChainableMethods<ChainableSubscription<T, TReturn>> {
  filter(predicate: (value: T) => boolean): ChainableSubscription<T, TReturn>;
}
```

**Comment by cowboyd** [comment]
Yeah, I think we have what we want with #178, but I also think that I thought I was using it improperly because I forgot to release v0.10.0

**Comment by cowboyd** [comment]
Maybe we can achieve the simplification of the conceptual model just by shuffling around the names? Specifically:

`ChainableSubscription` -> `Subscription`
`Subscription` -> `SubscriptionIterator`
`Chain` -> `SubscriptionBuilder`
