### ISSUE TITLE
Change names of subscription interfaces.

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/effection#187]
In order to tamp down the number of interfaces that you need to import and work with in order to use subscriptions, I think it will be helpful to shuffle the naming a bit, since `ChainableSubscription` is a bit of a mouthful, and it's unclear what exactly a subscription _is_ within the ecosystem. I'd like to propose renaming `ChainableSubscription` to `Subscription` since that is what is most often found on the left hand side of an assignment, and what needs to be typed most often by hand. More than that though, this is the interface that folks will use most. To make room, the razor-thin iteration API, we can rename what is currently `Subscription` to `SubscriptionIterator`:

```ts
export interface SubscriptionIterator<T,TClose> {
  next(): IteratorResult<T,TClose>;
}
```

**Comment by jnicklas** [comment]
Using `SubscriptionIterator` is much better. In my `mini-effection` spike I opted for the following naming, which is another decent option, IMO.

- `Subscription` -> `OperationIterator`
- `Subsribable` -> `OperationIterable`
- `ChainableSubscription` -> `Subscription`
- `ChainableSubscribable` -> `Subscribable` (I didn't actually implement this)

**Comment by cowboyd** [comment]
> Subscription -> OperationIterator

If we make the type of Operation recursive, then an "OperationIterator" is really just another type of operation?

```ts
type Operation<T> = Promise<T> | Iterator<Operation<unknown>, T>
```

**Comment by jnicklas** [comment]
@cowboyd I don't think so, the same way that `AsyncIterator<T> != Iterator<Promise<T>>`, an OperationIterator is not quite an iterator over operations.

**Comment by cowboyd** [comment]
I agree, but that's why I think exploring a different nomenclature is warranted. The sentence "an AsyncIterator is not an iterator over promises" is not confusing, whereas the sentence "An OperationIterator is not an iterator over operations" is.

**Comment by jnicklas** [comment]
Ahh, I see, that's true.

`EffectionIterator` and `EffectionIterable` would be other options which might make sense?

**Comment by cowboyd** [comment]
What's our equivalent of `Async` here? `Effect`? `EffectIterator`?
