### ISSUE TITLE
Cleanup build

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/effection#198]
When wondering why there were failing checks, I looked and saw that we still had the CircleCI webhook enabled. After disabling that webhook and check, I noticed we still have a couple things to do:

1. It looks like we're doing both `branch` and `pr` builds. This is good, but shouldn't we be only doing one build per platform? Ideally we would do `branch` builds, but with the the merge commit so that we can begin building as soon as a branch is pushed or commits are added to it. This is what CircleCI does. This might not be possible?
2. We should update our status badges to point to the github actions checks for all platforms. It's pointing to the CircleCI build which is quite out of date.

**Comment by jnicklas** [comment]
I think this is all good now?
