### ISSUE TITLE
promise returned by `main()`. reject on unexpected errors, resolve on expected errors

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/effection#203]
From https://github.com/thefrontside/bigtest/pull/627

>The way that this was implemented was to catch all non `MainError`s, but that felt not so great. It occurred to me that what might even be better would be to have the `Promise` returned from @effection/node` always resolve on both successful exits _and_ on `MainError` exits since these are still _expected_ outcomes. Only on an unexpected error would the promise actually reject. This would have the benefit of allowing custom error handling of unexpected exits, but baked in handling of all expected exits. In other words, we would have been able to write this as:

```ts
import { CLI } from './cli';
import { main } from '@effection/node';
import { unexpectedExit } from './unexpected-exit';

main(CLI(process.argv.slice(2)))
  .catch(unexpectedExit);
```

From the perspective of the `main()` operation, it would be consider a _successful_ exit when the operation either completes, or finishes with a `MainError` which indicates that the program raised the error. The only time the operation would fail would be on an unexpected error. Other things to consider:

- Don't return a raw `Context`, but a Promise implementor that has a reference to the context. That way, when you install a `catch` handler, it erases the default catch handler, or when you install a `then` handler, it erases the default tach handler. That way, there is full control about what to do when the process resolves.

**Comment by jnicklas** [comment]
Makes sense to me 👍

**Comment by jnicklas** [comment]
@cowboyd is this something we want to tackle for v2?

**Comment by cowboyd** [comment]
> @cowboyd is this something we want to tackle for v2?

Yeah, that would really clean things up, and I think it would also solve the "unhandled failure" problem we had seen before where unexpected errors get completely dropped on the floor because if `main()` returns a promise, and you don't have a catch handler, then it will get reported when an unexpected error happens.

Of course, if we just returned a promise and not a task, that would reduce the power of the caller, but maybe that's not a bad thing since `main()` really is intended to be a root entry point and nothing else.

**Comment by jnicklas** [comment]
> Of course, if we just returned a promise and not a task, that would reduce the power of the caller, but maybe that's not a bad thing since main() really is intended to be a root entry point and nothing else.

Hmm, this is actually a pretty significant downside, IMO. I've actually used the fact that main returns a task from time to time. For example with our `toString` debugging, it's pretty useful.
