### ISSUE TITLE
Split channel into sending and receive end

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/effection#205]
Currently channels are defined as a single class which has both sending and receiving ability. We could view the current channel type as follows:

``` typescript
interface Publishable<T> {
  send(message: T): void;
}
type Channel<T> = Publishable<T> & Subscribable<T>
```

But what we'd really want is something like this:

``` typescript
function channel<T>(): [Publishable<T>, Subscribable<T>] {
  // ...
}
```

So that we can split up the sending and receiving end. This is useful because we often want to hand out one "end" of the channel to someone else, yet retain control of the other end of the channel. If we hand out both ends of the channel, someone else might end up e.g. sending messages to the channel, which could break internal invariants.

This also neatly opens up the possibility of duplex channels:

``` typescript
function duplexChannel<Tx, Rx>(): [Publishable<Tx> & Subscribable<Rx>, Publishable<Rx> & Subscribable<Tx>] {
  // ...
}
```

Handing out one end of a duplex channel could work similarly and would be very useful e.g. for our connection server.

It could also be an option to make `Publishable` a simple function interface, but this makes the duplex case a bit more challenging.

``` typescript
interface Publishable<T> {
  (message: T): void;
}
```

An open question is a good convention as to the naming of the variables that we'd assign:

``` typescript
let [???, ???] = channel();
```

**Comment by jnicklas** [comment]
Investigating this a bit further, we can think about three distinct types of channels:

```
type ClassicChannel<T> = Publishable<T> & Subscribable<T>;
type SplitChannel<T> = [Publishable<T>, Subscribable<T>];
type DuplexChannel<T, R> = Publishable<T> & Subscribable<R>;
```

IMO, all three of these are valid and have their usecases, so we should probably provide all three of them? The question is what to name them, specifically the first two? And what would an API to create these look like?

Another question is how to handle `close`. How would one close a split or duplex channel? Which end needs to be closed for a split channel, the sending or receiving end? Can both ends of a duplex channel be closed?

**Comment by cowboyd** [comment]
Let's try to enumerate use-cases.

1.  You want to broadcast stuff to a bunch of places. This is where we have a single publisher, multiple subscribers. This is our basic event emitter subscription. In this case,  you have you classic channel where single publisher broadcasts messages of a single type `T`

```ts
type Send<T> = (message: T) => void;

let [send, receiver]: [Send<T>, Subscribable<T>] = createBroadcast<T>();
```

2. You have two communication endpoints that serve as a primary connection between two different systems. This the case that we have in the `Orchestrator`/`Agent` relationship, or the `Client`/`Orchestrator` relationship. Each endpoint is created independently, but the type of the send/receive are completely different;

```ts
type Send<T> = (message: T) => void;
let [send, outgoing, receive, incoming]: [Send<S>,Subscribable<S>, Send<R>, Subscribable<R>] = createEndpoint<S,R>();
```

In this case, you would create the endpoint and then hand out the `send()` function and the `incoming` `Subscribable<T>` to code on your side of the end point, and then hold onto `receive` and `outgoing` to negotiate the communications with the other end. In other words, `send()` publishes to `outgoing`, and `receive()` publishes to `incoming`

Are there other use cases?
