### ISSUE TITLE
pass argv: string[] to main operation

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/effection#214]
`@effection/node` main() is designed to implement the main method of a node process and yet we don't actually do the work of coupling to `process.argv` which has to be done manually, but in fact this is something that you invariably need to do.

Proposal, instead of

```ts
function main(operation: Operation<T>): Context<T>;
```

should be:

```ts
function main((argv: string[]) => Operation<T>): Context<T>;
```

That way

```ts

import { main } from '@effection/node';

main(function*() {
  yargs(process.argv);
});
```
becomes

```ts
import { main } from '@effection/node';

main(function*(argv) {
  yargs(argv);
});
```

**Comment by jnicklas** [comment]
Not sure I agree with this. E.g. if you're using `yargs` it will look at `process.argv` without having to pass it in.

We could totally do this, but it feels a bit unnecessary to me. Using `process.argv` is fine, imo.

**Comment by cowboyd** [comment]
There are two isues: convenience and isolation. Right now, we're forcing a program to couple to a global context for argument processing. That'll always be an option, but also passing in the arguments as an argument in this way let's your operation be used in any context, for example a unit-testing context.

**Comment by jnicklas** [comment]
@cowboyd given that `main` now also works in the browser, do you still feel we should do this, since there isn't really an equivalent to argv in the browser?

**Comment by cowboyd** [comment]
> @cowboyd given that `main` now also works in the browser, do you still feel we should do this, since there isn't really an equivalent to argv in the browser?

We could say `[]` in the browser, but I don't feel strongly about this. I say let's not do it now since it can be a forward compatible change if we decide to do it later, but it will not be a backwards compatible change if we decide we don't want it in the future
