### ISSUE TITLE
Proper mocha integration

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/effection#247]
I'd like to replace all of the hacky ad-hod `World` stuff that we have in BigTest with a more streamlined interface which allows us to interact with effection more easily in mocha tests. My first thought was to attempt to make a better version of the `World` interface, but there are a lot of problems we run into. Basically it is challenging to distinguish how and when errors should be propagated. It struck me that effection already solves all of these problems, so why not just double down on effection? We could with pretty minimal effort build something like this:

``` typescript
import { describe, it, beforeEach } from '@effection/mocha'

describe('describe is just a reexport', () => {
  beforeEach(function*() {
    yield someOperation()
  });

  it('is an operation', function*(task) {
    let process = daemon(task, 'some-background-process');
    yield once('some', event);
  });
});
```

It will make it make it *much* easier to test effection based code, and get all of the halting and error handling just right.

One downside of this is that the style of testing we have in BigTest is very heavily based on using `beforeEach`, and this style does not mesh well with this:

``` typescript
import { describe, it, beforeEach } from '@effection/mocha'

describe('running a daemon in before each', () => {
  beforeEach(function*(task) {
    daemon(task, 'some-background-process');
  });

  it('will have killed off the daemon once we get here', function*(task) {
    // daemon has already been halted once we get here
  });
});
```

There might be some way of exposing some task which encompasses the whole test and is shared between `forEach` and `it` blocks, but I don't have a clear idea on how to access or pass this task around.

**Comment by cowboyd** [comment]
> There might be some way of exposing some task which encompasses the whole test and is shared between forEach and it

This is exactly what the `World` was right? Might be hubris, but I think that we can accomplish this pretty smartly where every test case gets its own task, but we use the same task for all `beforeEach` blocks, the `it` block, and all `afterEach` block:

```js
import { it: _it, beforeEach: _beforeEach, afterEach: _afterEach } from 'mocha';
export { describe } from 'mocha';

let world: Task;

_beforeEach(() => {
  world = spawn();
});

_afterEach(async () => {
  await world.halt();
})

export const beforeEach = (operation: Operation) => _beforeEach(runInWorld(operation));
export const it = (operation: Operation) => _it(runInWorld(operation));

// you should not need afterEach with `@effection/mocha` right?
export const afterEach = (operation: Operation) => _afterEach(runInWorld(operation));

//Runs operation, but uses `world` as the task always.
function runInWorld (operation: Operation) => async () => {
    if (typeof operation === 'function') {
      let result = operation(world);
      if (typeof result.next === 'function') {
        await world.spawn(function*() {
          yield* result; // drain the generator, but it has `world` as its task.
        });
      } else {
        await result;
      }
    } else if (operation == null) {
      console.warn('you probably didn't mean to block the tests forever by returning a null operation.');
    }else {
      await operation //=> it's a promise
    }
}
```

**Comment by cowboyd** [comment]
Actually, this might be a case that illuminates the "fork-ish" thing that we keep chasing. We keep brushing up against the need to run an operation in the context of the current task to "extend it", or "include" this operation. It's different than a `spawn()` because it is tied to the lifetime of the current task rather a child task.

```ts
function* operation(task) {
  // do a fork-ish thing.
  // task does not complete until `operation` is completed
  // the scope of this operation is the same as the task from which 
  // it was invoked.
  tasck.run(function*(scope) {
    scope === task //=> true, operations invoked with `run()` are passed the original scope, not a child.
  });

  task.spawn(function*(scope) {
    scope === task //=> false, scope is a child of task.
  });
}
```

With a primitive like this, it would make the `@effection/mocha` pretty simple, because the `beforeEach` and `it` would be a `run()` rather than a `spawn()`.
