### ISSUE TITLE
Rethink the `fetch` API

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/effection#250]
The current API of `@effection/fetch` is just a thin wrapper around the `fetch` API, but this API is not convenient when used within effection, especially with v2.

`fetch` is currently the only primitive in the effection library which both takes a scope AND returns an operation. Everything else does only one of these things. This creates some confusion around the scope of the request.

Current:

``` typescript
run(function*(task) {
  let request = yield fetch(task, 'some/url');
  let data = yield request.json();
});
```

An alternative:

``` typescript
run(function*(task) {
  let request = createFetch(task, 'some/url');
  yield request.send();
  let data = yield request.json();
});
```

Since it is inconvenient to have to create the request and then yield twice, and 99% of the time you just want the data, we could add a higher level API like this:

``` typescript
run(function*(task) {
  let data = yield fetchJSON('some/url');
});
```

An alternative is to call these `createRequest`/`requestJSON`/`requestText`, or maybe something else?

**Comment by cowboyd** [comment]
closed by #310
