### ISSUE TITLE
Current Task as default argument and Task elision

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/effection#257]
I am resurrecting an old idea to solve an old problem in a new way. This was a thought after a discussion that @cowboyd and I had yesterday around how passing in a `Task` as an argument is not intuitive.

This was the suggested new API for fetch:

``` typescript
run(function*(task) {
  let request = createFetch(task, 'some/url');
  yield request.send();
  let data = yield request.json();
});
```

What if we could write it like this:

``` typescript
run(function*() {
  let request = createFetch('some/url');
  yield request.send();
  let data = yield request.json();
});
```

No strange `task` variable and `createFetch` is just a regular old function!

The key to making this work is that in 99% of cases, the task that we want to send in is the task of the currently running function. It's a very rare thing that this is not the case! Effection used to have an API for getting a handle to the currently running task/context, but we removed this at some point. What if we brought it back, and then the signature of `createFetch` would look like this:

``` typescript
import { Effection } from 'effection';

function createFetch(url: string, options?: FetchOptions, scope = Effection.currentTask) {
  // ...
  scope.spawn(...)
  // ...
}
```

In the case where you do need to "widen" the scope of a created resource, you can manually pass the task in.

We could even provide a `spawn` free function, so that you don't have to pass in the task just for spawning:

``` typescript
import { run, spawn } from 'effection';

run(function*() {
  spawn(function*() {
    // ... do whatever ...
  });
  // continue here
});
```

The downside to this is that in the case where you *should* widen the scope, it might not be immediately obvious how to do it. We're adding some implicit magic here which could be a bit confusing.

One cool trick we can do is that the default for `Effection.currentTask` is the `root` task, this way we can actually call a function like `createFetch` outside of an operation! Another neat thing is that it makes `run` a subset of `spawn`, so we could get rid of `run` entirely and just do this:

``` typescript
import { spawn } from 'effection';

spawn(function*() {
  spawn(function*() {
    // ... do whatever ...
  });
  // continue here
});
```

**Comment by jnicklas** [comment]
I've had some thoughts about this and how it could relate to resource-like things.

To recap: a resource is a thing which needs to spawn tasks in the background. In `v1`, this was a formalized concept with the `resource` function, which did some very dark magic to make things work. In `v2` we have opted for a simpler approach, where resources are simply functions which take a task as an argument.

The proposal is to define a resource like this:

``` typescript
interface Resource<T> {
  use(scope: Task): Operation<T>;
}
```

A few key things to note:

- The method is called `use` instead of `run` like in our current experiments, this is so as not to confuse it with the `run(operation)` function.
- The `use` methods returns an operation, which allows for asynchronous allocation of resources.
- It is an interface, rather than just a function type, this allows us to do things like `yield exec(...).join()` and `exec(...).use()` on the same input parameters.

### How to use a resource

Basically a resource is used like this:

``` typescript
run(function*(task) {
  let thing = yield makeResource().use(task);
});
```

Since it can seem somewhat counterintuitive where `task` comes from, we add a shortcut on `Task` to invert the order here, sort of like `task.spawn`

``` typescript
run(function*(task) {
  let thing = yield task.use(makeResource());
});
```

This form can then also be used inside a resource to allocate other resources! (i.e. scope widening)

``` typescript
function makeResource(): Resource<Thing> {
  return {
    use: (scope: Task) => function*() {
      let otherResource = yield scope.use(someOtherResource)
      // ...
    }
  }
}
```

Finally, we can add a `use` function, just like `spawn` to ellide the usage of the explicit task:

``` typescript
run(function*() {
  let thing = yield use(makeResource());
});
```

**Comment by jnicklas** [comment]
Maybe we can even make `spawn` accept a resource, so we can use `spawn` for both usecases? Not sure if this would actually work, but it would remove the need to understand the distinction of `use` and `spawn` at least on the consumer side:

``` typescript
run(function*() {
  let thing = yield spawn(makeResource());
});
```

And it makes sense in that using `spawn` without a yield does not return a resource, the only difference here is that with this form, `spawn` can allocate things which outlive the yield point.

**Comment by cowboyd** [comment]
I like it! This is interesting. We keep circling around this idea of resources and computations being similar things. If we have an interface like `Resource` we can add things to it that will make debugging much simpler:

```ts
interface Resource<T> {
  use(scope: Task): Operation<T>;
  description?: string;
  state?: Record<string, unknown>;
}
```

etc....

**Comment by cowboyd** [comment]
However, in the context of free-standing functions, I'd think I'd prefer to have the scope-finding magic be "look at the parent when the operation is run" vs "look at the currently running task when the operation is created." This allows for the exact same usage when consuming, but allows for easier composition since it doesn't matter what context the operation is created in. 

In either cases when you need to widen scope, you'll have to call scope.use() explicitly.

**Comment by jnicklas** [comment]
> "look at the parent when the operation is run" vs "look at the currently running task when the operation is created."

I'm not quite sure what you mean by this, could you provide an example?

> In either cases when you need to widen scope, you'll have to call scope.use() explicitly.

Yes exactly. This would be limited to when you need to create your own resource, normally. For everything else, we shouldn't need to widen the scope.

**Comment by cowboyd** [comment]
```ts
import { createHttpServer } from '@effection/http';

run(function*(scope) {
  yield scope.use(createHttpServer());
});

run(function*() {
  yield use(createHttpServer());
});
```

If the above two are equivalent and we're finding an "implicit" scope, I think I'd rather it late-bind at runtime by automatically widening to the parent. Although honestly, if we could destructure task methods, it would be nearly as convenient to say: 

```ts
run(function*({ use }) {
  yield use(createHttpServer());
});
```

**Comment by jnicklas** [comment]
> Although honestly, if we could destructure task methods, it would be nearly as convenient to say:

The main reason to elide the task, is so that we eventually can get out of having to pass the task to the generator function entirely. This would enable us to do the whole `function* === async function` equivalence thing without any nasty hacks.

**Comment by jnicklas** [comment]
I actually realized a problem with this:

```ts
run(function*(scope) {
  let resourceTask = scope.spawn(makeResource());
  resourceTask.halt();
  // tasks spawned by resource are still running here
});
```

Unfortunately, halting the task returned by `spawn` will not actually terminate all of the tasks spawned by the resource, as one might expect.
