### ISSUE TITLE
Add operation combinators

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/effection#292]
There are a few combinators that we could add that come up sometimes which are useful. We should provide all methods available on Promise for intuitive interop:

- [x] `all`: completes when all the given operations complete, returns an array of results
- [ ] `allSettled`: like `all`, except it will not short circuit if any operation fails, and instead return an aggregate result
- [x] `race`: completes when any of the given operations complete, returns its result and halts all the other operations
- [x] `any`: like `race`, but some of the given may fail as long as at least one of them completes

Additionally, we might consider the following:

- [x] `timeout`: throws an error after the given amount of time (alt names: `throwAfter`, `failAfter`, etc...)
- [x] `timebox`: runs the given operation and throws an error if it has not completed after given amount of time (alt names: `withTimeout`, `withTimeLimit`, `withFailAfter`, etc...), this is essentially `race(op, timeout(x))`
- [x] `ensure`: runs the given operation on halt, basically `try { yield } finally { yield op }`, we could replace `task.ensure` with this, I think.

Anything else?

**Comment by cowboyd** [comment]
I've often wanted a general operation mapping function.

Also something to consider:

a form of `all` except instead of an array, it is a hash of named promises.

```ts
let { services, url } = all({
  services: getServices(),
  url: bindPort()
});
```

I used this quite a bit and preferred it to the array form of all in `RSVP` https://github.com/tildeio/rsvp.js#hash-of-promises

They actually called the method `hash()` but I think that's confusing since a hashing function is already a well established concept

**Comment by cowboyd** [comment]
@jnicklas another useful one might be a `capture()` combinator for when you want to programatically deal with error cases:

```ts
declare function capture<T, TErr = Error>(operation: Operation<T>): Operation<T | TErr>;
```

**Comment by jnicklas** [comment]
@cowboyd `captureError` is something we already have in the `@effection/mocha` package, and for writing tests it is extremely useful. I would be very open to moving this to core.

**Comment by jnicklas** [comment]
We're still missing `allSettled`, but I question the utility of that method. Let's close this out for now.
