### ISSUE TITLE
vulnerability of handlebars via @effection/node

### ISSUE THREAD

**Issue by nothingismagick** [thefrontside/effection#314]
Here is the dependency chain:

`@effection/node > ctrlc-windows > neon-cli > handlebars`

![image](https://user-images.githubusercontent.com/35242872/117536700-e4ca1380-affc-11eb-9c1f-3174499b43de.png)

Can you please resolve this @jbolda ?

**Comment by jbolda** [comment]
I believe this PR will take care of this.
https://github.com/thefrontside/ctrlc-windows/pull/26
