### ISSUE TITLE
Add subscription/stream method to spawn for each value

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/effection#332]
Often when writing servers, we want to loop over a subscription or stream, and handle each item in the stream. However, we normally do *not* want to block while we're processing the next item. For example, in a websocket server, all connections should be handled in *parallel*. The natural way of expressing this via `forEach` then does not work, since `forEach` processes all items in *series*. Essentially we should have a parallel version of `forEach`.

This is incorrect, since it processes requests in series:

``` typescript
function *runServer() {
  yield on(server, 'request').forEach(handleRequest);
}
``` 

This is correct, but cumbersome:

``` typescript
const runServer = () => function*(scope) {
  yield on(server, 'request').forEach(() => { scope.spawn(handleRequest) });
}
```

This would be nicer:

``` typescript
function *runServer() {
  yield on(server, 'request').parallelForEach(handleRequest);
}
```

Bikeshed: what is a good name for this method?

- parallelForEach
- parallel
- inParallel
- spawnForEach
- ... ?

**Comment by cowboyd** [comment]
My favorite of that list is `inParallel`. Other alternatives

* `parallelize(handleRequest)`
* `spawnEach(requestHandler)`
* `concurrently(handleRequest)`
* `forAll(handleRequest)`

**Comment by jnicklas** [comment]
Feeling that this is a bit of a red herring. The usecase I outlined above does not work for this usecase, since the connection needs to be scoped to a block, and closed when that block exits or errors. This is not possible with an external iteration API, and requires some kind of callback based solution. Are there other usecases for this feature? I'm feeling that there probably are, but until/unless we have concrete ones, maybe we shouldn't add this?

**Comment by cowboyd** [comment]
Perhaps you're right. I've been thinking of some sort of more general API for a "spawn point" that let's you control the concurrency profile of an operation declaratively:

```ts
let handleRequest = scope.createSpawnPoint({
  maxConcurrency: 100, 
  drop: 'latest',   
  *operation(request, response) {
    // do body;
  },
  *dropped(request, response) {
    response.statusCode = 503
    response.statusText('too many open requests')
    response.end();
  }
});
```

```ts
// then in your server code.

app.post('/some-url', handleRequest);
```

Then, when `scope` is halted, it just stops handling requests completely.

**Comment by cowboyd** [comment]
This could also serve as a more general purpose gateway from non-effection code to effection code than a raw `run()` which currently needs to have a `task.state` check wrapped around it. For example, you could implement an autocomplete by just tweaking your spawn parameters.

```jsx
let [results, setResults] = useState();
let doSearch = scope.createSpawnPoint({
  maxConcurrency: 1,
  drop: 'oldest', // drop any currently running search
  *operation(q) {
    yield sleep(50);
    try {
      let json = yield fetch(`${url}?q=${q}`).json();
      setResults(json);
    } catch (error) {
      setError(error);    
  }
})
return 
<div>
  <input onInput={doSearch} />
  <ShowResults results={results} />
</div>;
```

**Comment by cowboyd** [comment]
This will be provided by `TaskGroup` whenever that lands.
