### ISSUE TITLE
Way to synchronize on async operations inside a halt()

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/effection#35]
Sometimes you want to do asynchronous cleanup. For example, in `@bigtestjs/server` we would really like the parcel server halt code. Unfortunately, you cannot yield inside a generator that has already returned or thrown. We'd like the halt() to not be considered complete until some async code has run. e.g.

```js
let bundler = new Bundler();
try {
  yield;
} finally {
  yield bundler.stop() <-- cannot be done.
}
```

**Comment by jnicklas** [comment]
Somewhat related to this: it should also be possible to yield to a halt. Ideally, I think, `halt` should return a promise, since we may also want to do this from outside of the effection world, e.g.:

``` javascript
afterEach(async function() {
  await someExecution.halt()
});
```

**Comment by jnicklas** [comment]
This is now implemented in v2.
