### ISSUE TITLE
Non-magical resources

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/effection#358]
In seeing how resources can be confusing, and also trying to blog about effection and trying not to explain effection without having to jump right into resources, it made me wonder if there was a way we could enhance the primitives and avoid the need for resources entirely. 

Essentially, a resource is just an operation that runs in the calling scope rather than the local scope, and, to that end, resources init functions have the form

```ts
delcare function init<T>(scope: Task, local: Task<T>): Operation<T>;
```

where `scope` is the scope of the caller, and "local" is the scope of the `init` function. That's because what you're most interested in within a resource is the caller, so `scope` is bound to that, and `local` is bound to what we would otherwise think of as the scope if we weren't just executing normally. This is the opposite of what you have in a "normal" operation, where the first argument is the current scope.

This is confusing, and while we entered into this knowingly, it still is a gotcha that has gotten pretty much everyone who is just looking at the sources. I feel like just reading the source code of a resource should help to understand resources rather than having a WTF moment and then needing to discover resources.

I think we could achieve this by adding a `caller` reference to a task. That way, there is no magic switch-er-roo to the scope which is passed to the operation. For example, the following server resource from simulacrum:

```ts
export function createServer(app: Application, options: ServerOptions = {}): Resource<Server> {
  return {
    *init() {
      let server = app.listen(options.port);
     
      yield spawn(function*() {
        try {
          let error: Error = yield once(server, 'error');
          throw error;
        } finally {
          server.close();
        }
      });

      if (!server.listening) {
        yield once(server, 'listening');
      }

      return {
        http: server,
        address: server.address() as AddressInfo
      };
    }
  };
}
```

could be written as:

```ts
export function createServer(app: Application, options: ServerOptions): Operation<Server> {
  return function*({ caller }) {
    let server = app.listen(options.port);

    caller.spawn(function*() {
      try {
        let error: Error = yield once(server, 'error');
        throw error;
      } finally {
        server.close();
      }
    });

    if (!server.listening) {
      yield once(server, 'listening');
    }

    return {
      http: server,
      address: server.address() as AddressInfo
    };
  }
}
```

This accomplishes the exact same thing without forcing developers to first parse the execution context (resource or operation) first before trying to understand the code. Instead, there is just one set of rules. Looking at this it is very clear even if you aren't familiar with resources exactly what is going on.

I worry that in our quest to hide the `caller` of a task, we might have made it harder than if we just let you work with the caller directly.

**Comment by jnicklas** [comment]
This is essentially the same system we had in Effection pre resources, and the problem with this system is that it does not compose well. If you have two operations which use the caller and you want to use one within the other, then you have a problem. There are many ways to approach to solve that problem, but suffice to say that just accepting the caller itself is not enough to solve the problems that resources solve. This is precisely the reason we invented resources in the first place.

**Comment by jnicklas** [comment]
@cowboyd can we close this issue?

**Comment by cowboyd** [comment]
Yes I think we can
