### ISSUE TITLE
task.spawn as operation

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/effection#360]
Working in code, and writing explainers, it's clear that whenever you `spawn`, it is safest as an operation. In fact, there is the standalone operation `spawn(operation)` and `spawn(operation).within(scope)`. But there is a cognitive dissonance between method `spawn` and operation `spawn`. Method spawn is needed for integration from outside an effection tree, but when working from within an operation, you always want to use operation `spawn` because it is safer.

I propose renaming `task.spawn` to `task.evaluate`, and introducing `task.spawn` as an operation. That way instead of saying

```ts
yield spawn(operation).within(scope);
```

you can instead just say:

```ts
yield scope.spawn(operation);
```

Because let's face it, when you find out at the end of reading an operation which scope it will be in, it's going to be a nasty suprise. E.g.

```ts
yield spawn(function*() {
  yield doThis();
  yield doThat();

  yield spawn(function*() {
    yield doOtherThing();
    yield doYetSomethingElse();
 });
}).within(scope) // psyche! It's in the parent. I hope you were paying attention!!!
```

by making `spawn()` mean the same thing in every context, it cuts down on potential confusions. In other words, `spawn` is `spawn`, and it's what you use within operations to start other concurrently executing operations. `task.evaluate(operation)` is something else entirely and what you use _outside_ of operations.

**Comment by jnicklas** [comment]
I'm not entirely opposed to this, it makes sense semantically, IMO.

We should be clear that this is a pretty significant API change at the 11th hour, but maybe that is justified.

We'd need to bikeshed the name of the current spawn method though. I feel like `evaluate` is confusing, it sounds like the operation is evaluated within the context of the task, which is not the case, it runs as a child. Last time around we discussed `run`, but it has the same issue.

**Comment by cowboyd** [comment]
I'll throw together a PR today.
