### ISSUE TITLE
Add workflow to generate and publish documentation

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/effection#383]
We want to have an automated workflow which generates and uploads the documentation.

- [ ] When should this be done? On release of a new version, or for each commit?
- [ ] Should we use GitHub actions or CircleCI, since we use both on this repo
- [ ] How should the docs be hosted?
- [ ] Should we keep old versions of docs around?

**Comment by minkimcello** [comment]
> How should the docs be hosted?

Jorge put together a template [here](https://deploy-preview-276--effection.netlify.app/effection/docs/use-cases/typeahead/) on Netlify. Is that what you're referring to by hosting?

> When should this be done? On release of a new version, or for each commit?

Ideally we should update the website at the same time the new changes are released (when we merge the Version Packages PR created by changeset). I think we can call netlify [build hooks](https://docs.netlify.com/configure-builds/build-hooks/) to trigger new deploys so we could configure a new workflow to run on the base branch but only if the commit author is frontside jack and have it run the `curl` command.

> Should we use GitHub actions or CircleCI, since we use both on this repo

I think we should make this decision after we figure out what's required of our CI workflow? I want to say we should migrate back over to CircleCI as much as possible but I don't know if we want to keep one foot in Github Actions to keep an eye on it (in hopes they'll catch up in speed/reliability).

> Should we keep old versions of docs around?

I noticed when I was trying to bump effection to a specific version, there was a lot of jumping back and forth on github to dig around the source code of different versions. So given the nature of effection, I think it would be wildly helpful to have older version API docs like ember does:
![Screen Shot 2021-06-14 at 12 19 30 PM](https://user-images.githubusercontent.com/29791650/121925976-74a16280-cd0b-11eb-8b5b-f239c09416a6.png)
