### ISSUE TITLE
Add `AbortSignal` resource

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/effection#589]
[AbortSignal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) is a standard JavaScript mechanism for signalling cancellation. In fact, we use it inside `@effection/fetch`. However, for integration with _any_ 3rd party library that uses abort signals as native `fetch()` does, it would be really nice to have the ability to quickly create an abort signal that is tied to the current task's scope, and then uses it as a connection between that task and the 3rd party:

```js
function* request() {
  let signal = yield createAbortSignal();
  return yield fetch('/some/url', { signal });
}
```

steps:
- [ ] refactor @effection/fetch to use an abort signal resource internally.
- [ ] move abort signal resource to either its own package or `@effection/core` and export from `effection`
- [ ] add typedocs

**Comment by taras** [comment]
@cowboyd  can you write the docs for this before implementation so it gets done right away?

**Comment by cowboyd** [comment]
There's the matter of the typedocs and the guides. Here's the typedoc:

```ts
/**
 * Create an [`AbortSignal`](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) bound 
 * to the current scope. Whenever that scope is completed, errored, or halted, the abort signal will 
 * be triggered.
 *
 * Cancellation and teardown is handled handled automatically in Effection, but in systems where
 * it is not, the lifespan of a transaction needs to be explicitly modeled. A very common way to do this is with 
 * the `AbortSignal`. By creating an abort signal bound to an Effection task, we can pass that signal down to 
 * 3rd party consumers that can use it to register shutdown callbacks that will be invoked whenever the task is done
 * (either by completion, failure, or cancellation). An example is the native [`fetch()`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch#syntax) API which takes a `signal` parameter in order to trigger when the HTTP request should
 * be cancelled.  This is how you would bind the lifetime of the HTTP request to the lifetime of the current task.
 * 
 * ```js
 * function* request() {
 *   let signal = yield createAbortSignal();
 *   return yield fetch('/some/url', { signal });
 * }
 * ```
 */
```

@jnicklas where do you think this should slot into the guides?

**Comment by jnicklas** [comment]
@cowboyd I think the most natural place would be in the lifecycle guide, just after `ensure` https://frontside.com/effection/docs/guides/lifecycle#ensure

<blockquote><img src="https://frontside.com/effection/images/meta-effection.png" width="48" align="right"><div><strong><a href="https://frontside.com/effection/docs/guides/lifecycle">Task Lifecycle | Effection</a></strong></div><div>We have talked about how Effection operations are able to clean up after</div></blockquote>

**Comment by cowboyd** [comment]
I can add the section to the guides once we have the new version merged, but I don't think this should hold up implementation. 

@minkimcello  I think this is ready to go 👍🏻

**Comment by minkimcello** [comment]
Shouldn't we add the docs at the same time it's implemented?

**Comment by cowboyd** [comment]
I will add the docs to the guides, yes, but it shouldn't block the implementation. I can add them to your PR so they go in at the same time. For the actual code, the Typedoc is provided above.
