### ISSUE TITLE
Holistically rethink Effection's foundational analogy and nomenclature

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/effection#66]
The new mechanics of effection are more on point: It's a tree of "node thingies" each of which is either running, or finished running because it encountered an error, it was explicitly halted, or it returned a result and there are no child "node thingies" which are still running. Anything that changes the state of these "node thingies" must be in the form of an operation that runs in the context of an on-going computation.

But we got there by looking at the problem through a bunch of different paradigmatic lenses: algebraic effects, Erlang processes, structured concurrency, delimited continuations, promises, etc... It's no surprise that the resulting vocabulary used in the codebase for both private and public APIs reflects this diversity. So we have things like `fail` and `ensure` borrowed from Ruby, `resume` from delimited continuations, `ExecutionContext` from algebraic effect, `spawn` from Rust, and so on.

Lateral thinking is critical when developing something novel, but the resulting hodge-podge of terminology interferes with a shared understanding of what exactly Effection is and what problems it is effective to be used for.

In my opinion we should proceed with the APIs that we have now, since mechanics are going to be mechanics, but prior to a public release, we need to come up with a foundational analogy of what Effection trees are, and let the vocabulary flow from there. In other words, every method and every property should align with the foundational analogy. Also, we want to choose something that lowers the bar the most towards wider adoption.

Let's use this issue to discuss possible alternatives that we'd feel good about going 1.0 with. Here's an example (which is deliberately different than anything we've talked about before):

#### state: 
* Transaction.isRunning
* Transaction.isWaiting
* Transaction.isSuccessful
* Transaction.isFailed
* Transaction.isCancelled
* Transaction.isOpen (isRunning | isWaiting)
* Transaction.isClosed (isSuccessful | isFailed | isCancelled)
* Transaction.parent: Transaction

#### controls:
* `Transaction.complete(result)`
* `Transaction.fail(error)`
* `Transaction.cancel(reason)`
* `Transaction.run(operation)`
* `Transaction.onClose()`

**Comment by jnicklas** [comment]
I think we can close this issue, since it is somewhat out of date. We have found some nice new nomenclature and foundational primitives in `v2`.
