### ISSUE TITLE
Rename `main` and add a more oppinionated `main`.

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/effection#68]
So I was looking at some of the code in bigtest-server, and it struck me that whenever we bootstrap effection at the top level, we have to do a dance to attach a signal interrup handler and stuff. Not only is this annoying, it's also error prone, since there are some subtle details we could get wrong.

In the more comprehensive effection PR, @cowboyd added a `interrubtible` higher order operation(?) which basically turned any operation into one with proper signal handlers.

While this is an okay solution, maybe we can do even better. I propose that we add this to Effection itself. Obviously since it uses `process`, it will be specific to Node, and not work when running Effection in e.g. a browser.

If we rename the current `main` function to `run` or something similar, we can make a more specific main function which lives under a separate path. So something like:

``` typescript
import { main } from 'effection/node'
```

What do you think?

**Comment by cowboyd** [comment]
I agree whole-heartedly. I have yet to come across a effection program that I didn't want this installed. We could rename the current `main` -> `enter`, `spawn`, `start` or something.

I actually think we should go ahead and release a completely separate NPM package for `@effection/node` so that the code is never even bundled when you try and use it from a webpage, or from deno.

That means we need to [convert effection into a multi-repo](https://github.com/thefrontside/effection.js/issues/71)

**Comment by jnicklas** [comment]
Does  it need to be a separate package for it not to be loaded? Can't it just be a separate path to require? Or maybe this depends on how the tree shaking is implemented in the builder?

**Comment by cowboyd** [comment]
In theory, it should not be necessary, but in practice, it's expected that NPM packages are shipped transpiled already into a format that can be used by the target platform. Tree shaking should be straightforward on the source, but when we distribute, we have to place it into `dist-node/index.js` and `dist-web/index.js` which is unreliable at best, impossible at worse to tree-shake.

In an ideal world, we would declare which language features we use and the final target app, _and only the final target app_ would over do any transpilation. Sadly, that's not how JavaScript works in 2020 😢

**Comment by cowboyd** [comment]
Of course, it can be there if you never require it, and I don't think that would be a problem for most server side developer if there was web-only code shipped along with the package, but the reverse is not true. A very large segment of web developers care a lot about shipping code that will never run.

**Comment by jnicklas** [comment]
Duplicate of #130
