### ISSUE TITLE
Convert effection into a multi-repo

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/effection#71]
There are now a lot of add-on helper functions for using effection in different platforms. When using node, there are certain things that we need, when in the browser there are others, and there are some that are in both. Thus far, we have definite need of the following npm packages

* `@effection/events`
  * `on()`, 
  * `monitorErrorsOn()`
* `@effection/node`
  * `main()`

And in the future, we can generalize some of our current helpers into things like:

* `@effection/websocket`
* `@effection/express`

Let's put this stuff into a monorepo with transparent publishing.

**Comment by jnicklas** [comment]
This is done.
