### ISSUE TITLE
Current documentation is broken (non-navigable)

### ISSUE THREAD

**Issue by madskaddie** [thefrontside/effection#766]
The links  at https://frontside.com/effection/api/index.html have wrong hrefs

I could check some documentation by making the href relative in the browser's inspector, for example:

```
<li>
  <a href="/modules/_effection_core">@effection/core</a>
</li>
``` 
->

```
<li>
   <a href="modules/_effection_core">@effection/core</a>
</li>
```

**Comment by cowboyd** [comment]
@madskaddie Thanks for reporting this! Let's get this fixed.

**Comment by cowboyd** [comment]
Hi @madskaddie! We have fixed the links for the V2 type-docs and it can be found here https://frontside.com/effection/V2/api/index.html

However, note that we are in the process of releasing V3, and the type documentation is hosted on deno.com 

Here is the link to the V3 website https://frontside.com/effection

<blockquote><div><strong><a href="https://frontside.com/effection/V2/api/index.html">Effection API Reference</a></strong></div><div>Documentation for Effection API Reference</div></blockquote>
<blockquote><img src="/assets/images/meta-effection.png" width="48" align="right"><div><strong><a href="https://frontside.com/effection/">Introduction | Effection</a></strong></div><div>Effection is a structured concurrency and effects framework for JavaScript.</div></blockquote>
