### ISSUE TITLE
Settle on API for `createSignal()`/`createQueue()` and `createChannel()`

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/effection#796]
There are two "styles" of API for our built in streaming and subscription, the signal/queue and the channel. 

#### Signal/Queue

```ts
let { ...signal, stream } = createSignal();
```

```ts
let { ...queue, subscription } = createSubscription();
```

#### Channel

```ts
let { input, output } = createChannel();
```

## Alternatives

Which of these should we choose? Should we try something different? Maybe an array destructure?

```ts
let [channel, stream] = createChannel();
```

```ts
let [queue, subscription] = createQueue();
```

```ts
let [signal, stream] = createSignal();
```

**Comment by neurosnap** [comment]
My only concern with array destructure is when you have multiple channels in a single function body.  Now users need to destructure with special names for every channel.

**Comment by cowboyd** [comment]
@neurosnap Yeah, that makes sense. I'm also wondering if `Stream`/`Subscription` is just too confusing to place in parallel with `Iterable/Iterator` `AsyncIterable/AsyncIterator`... maybe would should just make the parallel really stupidly straightforward: `YieldIterable/YieldIterator`; It doesn't really make much sense, but it does at least keep the symmetry.

There's so much explaining that has to happen to convey the relationship between `Stream` and `Subscription`. What if it was just:


```ts
interface YieldIterable<T, TClose> {
  [Symbol.iterator](): Operation<YieldIterator<T, TClose>>;
}

interface YieldIterator<T, TClose> {
  next(): Operation<IteratorResult<T, TClose>>;
}
```

Again, out of context `YieldIterable` doesn't make much sense, but in the context of drawing symmetry with `AsyncIterable` it perhaps does... 🤷🏻‍♂️
