### ISSUE TITLE
Remove stream processing packages?

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/effection#797]
In the spirit of keeping things "core", perhaps stream processing functions `first()`, `filter()`, `map()`, `pipe()`, etc... should be removed from the core API, and published as a separate library.

**Comment by neurosnap** [comment]
If this were my project I wouldn't move them into a separate package.  It's clear users are getting fatigued from having to import a ton of libraries -- especially for a single tool.

You could do a sub-module `effection/streams` but then would everything related to a stream go there?  There could be dependency issues between core and stream to sort out, unclear atm.

For me, the reason to create a separate package is if there are dependencies the end-user might not want to install for every project.  So if those `stream` functions required some other heavy dependencies then I think it would make more sense to separate them.
