### ISSUE TITLE
Docs typos

### ISSUE THREAD

**Issue by rrthomas** [thefrontside/effection#902]
In https://frontside.com/effection/docs/collections "equilavent" should be "equivalent".

**Comment by rrthomas** [comment]
Another one in https://frontside.com/effection/docs/actions where there is a link to http://localhost:8000/docs/operations#cleanup !

**Comment by rrthomas** [comment]
Something also went wrong on example 4 of https://deno.land/x/effection@3.0.3/mod.ts?s=call:

"Because call() runs within its own [Scope](https://deno.land/x/effection@3.0.3/mod.ts?s=Scope), it can also be used to establish * establish error boundaries https://frontside.com/effection/docs/errors | error boundaries."

**Comment by rrthomas** [comment]
Another broken link: https://frontside.com/effection/v3/docs/operations (which does not exist) is linked to from https://deno.land/x/effection@3.0.3/mod.ts?s=Operation

**Comment by cowboyd** [comment]
@rrthomas Thank so much for the detailed proof read! I've put together a PR to address all of the issues you found. Thank you so much for this!

**Comment by rrthomas** [comment]
You're welcome, thanks for Effection!
