### ISSUE TITLE
Effection breaks when regenerator runtime is minified and thoughts about supervisors

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/effection#91]
So our old issue with recognizing when a generator is a generator came up again :(

Currently we do this like this:

https://github.com/thefrontside/effection.js/blob/b8d72eefa6570f12a1767e5fcb6b29b5b1af4578/packages/effection/src/generator-function.js#L1-L5

But apparently, sometimes when regenerator-runtime is minified it will actually minify the constructor name as well. So our generator function gets not recognized as such. This basically boils down to an old problem:

``` javascript
function a({ resume }) { resume("foo") }
function* b() { yield "foo" }

main(function*() {
  yield a;
  yield b;
});
```

Here Effection has to "know" that it should call `a` with the controls (because it is a controll function), but it should convert `b` into a generator controller.

I think some of this problem will probably go away as we find new internal primitives, but there is a core issue here which is kind of interesting:

generator functions are functions which return a generator

In other words, the creation of the generator is lazy.

This is potentially quite profound. Consider the following code:

``` javascript
function* runServer() {
  let server = new Server();
  yield server.listen();
  yield server.join();
}

// ... somewhere else
yield spawn(runServer);
```

What happens when the server shuts down? Suppose we want to restart it automatically, we could create a supervisor which does this. Wouldn't it be nice if we could just do this:

``` javascript
function* runServer() {
  let server = new Server();
  yield server.listen();
  yield server.join();
}

// ... somewhere else
yield supervise(runServer);
```

We didn't have to change `runServer` at all! Yet, we could have a supervisor which simply re-runs the passed operation! This is amazingly powerful!

This only works though if *all* of our operations are thunks. Generator functions are already thunks of course. Let's look at how we'd write that previous example:

``` javascript
function a() { return ({ resume }) => resume("foo") }
function* b() { yield "foo" }

main(function*() {
  yield a;
  yield b;
});
```

There is no longer any ambiguity! The return value of `a` is a function and the return value of `b` is a generator, these are very easy to distinguish from each other!

This is also part of the design of trio, one of the libraries which inspired Effection, and it is [mentioned in the structured concurrency blogpost](https://vorpus.org/blog/notes-on-structured-concurrency-or-go-statement-considered-harmful/#you-can-define-new-types-that-quack-like-a-nursery) that inspired Effection.

Just some random rambling thoughts!

**Comment by jnicklas** [comment]
One  disadvantage of implementing this is that we currently support patterns like this:

``` javascript
function* createServer(port) {
  let server = new Server();
  yield server.listen(port);
}

// ... somewhere else
yield createServer(1234);
```

This would now have to be written like this:

``` javascript
function createServer(port) {
  return function*() {
    let server = new Server();
    yield server.listen(port);
  }
}

// ... somewhere else
yield createServer(1234);
```

**Comment by cowboyd** [comment]
I think that if we assume that `supervise` will take arguments to be passed into the generator, then we can pass arguments to create server via supervise

```ts
unction* runServer(port: number) {
  let server = new Server();
  yield server.listen();
  yield server.join();
}

//...somewhere else

yield supervise(runServer, 3000);
```

Overall, I'm really excited about a new architecture that we can live with for a very long time. I've been thinking about this a lot over the weekend, and I think that there are some new universal constraints we should consider that will make things significantly more powerful and composable;

1. Everything is generator, even low-level operations.... the only synchronous effection methods that you should call are `resume/fail`, and even then, only of the current operation (resuming or failing operations other than the current one, should be done with `resume/fail` operations.
2. Everything is a resource... an object paired to a computation, and it is resources that you deal with primarily in user-space, and that form the effection tree/stack. Operations can return resources in which case their lifecycle is promoted. For example, spawns and forks would themselves be resources.

In fact, I'm thinking that you might have finally found the elusive `Effect` primitive that we've been looking in for in the form of `Resource`. It's been odd, that we have a library called effection, but no `Effect` entity. I'm thinking that data + computation might be just that.

Anyway, excited to explore these things soon!

**Comment by jnicklas** [comment]
I would like to discuss this again with regards to v2, there are some tradeoffs to be made which we need to decide on.
