### ISSUE TITLE
Express `ExecutionContext` lifecycle with a generator?

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/effection#94]
We drive state changes in our effection apps with generators because they are so much clearer as to what's going on, but inside effection itself we use timed callback methods to assemble what is going on. It got me thinking that even if we don't use a unified mechanism, it would be much, much clearer if we could express the context procession as a generator (or maybe an async?) function:

```js
export function* lifecycle() {
  try {
    this.state = 'pending';
    let result = yield this.operation;
    this.state = 'waiting'
    yield awaitRequiredChildren();
    this.state = 'completed';
    return result;
  } catch (error) {
    this.state = 'errored';
    this.error = error;
    return error;
  } finally {
    yield haltAllChildren();
  }
}
```

**Comment by jnicklas** [comment]
v2 will probably use async/await for the implementation, which will function sort of similarly to using a generator.
