### ISSUE TITLE
Example in Documentation doesn't work as mentioned

### ISSUE THREAD

**Issue by geohuz** [thefrontside/effection#945]
The following example code in the https://frontside.com/effection/docs/errors, 

```javascript
import { main, suspend } from 'effection';
import { tickingBomb } from './ticking-bomb';

await main(function*() {
  yield* spawn(tickingBomb);
  try {
    yield* suspend(); // sleep forever
  } catch(err) {
    console.log("it blew up:", err.message);
  }
});
```

> You might be surprised that **we do not enter the catch handler** here. Instead, our entire main task just fails...

Running the program I saw the output: it blew up: boom

**Comment by cowboyd** [comment]
That is the expected behavior. To catch errors in concurrent processes you must establish an error boundary first.
